// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPHx_-QOQi1m8Q0hfHdj-bTx5RfRo_kbw',
    appId: '1:392607224274:web:b645390e42d2fdb3c3780b',
    messagingSenderId: '392607224274',
    projectId: 'ratipi-app',
    authDomain: 'ratipi-app.firebaseapp.com',
    storageBucket: 'ratipi-app.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_s8WECg7ij4rcdx8YIceiBaaFToSaHHQ',
    appId: '1:392607224274:ios:a64718da435e1c19c3780b',
    messagingSenderId: '392607224274',
    projectId: 'ratipi-app',
    storageBucket: 'ratipi-app.appspot.com',
    iosBundleId: 'com.example.exploreFultter',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_s8WECg7ij4rcdx8YIceiBaaFToSaHHQ',
    appId: '1:392607224274:ios:a64718da435e1c19c3780b',
    messagingSenderId: '392607224274',
    projectId: 'ratipi-app',
    storageBucket: 'ratipi-app.appspot.com',
    iosBundleId: 'com.example.exploreFultter',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvMhfFognJsAO3fEMz5NS01morROtYFVU',
    appId: '1:392607224274:android:e3224f37db0dc312c3780b',
    messagingSenderId: '392607224274',
    projectId: 'ratipi-app',
    storageBucket: 'ratipi-app.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPHx_-QOQi1m8Q0hfHdj-bTx5RfRo_kbw',
    appId: '1:392607224274:web:ae53c87940503fe0c3780b',
    messagingSenderId: '392607224274',
    projectId: 'ratipi-app',
    authDomain: 'ratipi-app.firebaseapp.com',
    storageBucket: 'ratipi-app.appspot.com',
  );

}